<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AUTO2000 DIGIROOMDealer Toyota terbesar_d961b6</name>
   <tag></tag>
   <elementGuidId>b5fb4440-8639-42b9-b407-0b1fdc88e979</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8b3809ad-26e2-410c-8562-49494a760420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-reliableBlack bg-[#f4f4f4] py-3 lg:py-11 flex justify-center</value>
      <webElementGuid>19771c55-bc23-4902-940b-f662366b49ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AUTO2000 DIGIROOMDealer Toyota terbesar di Indonesia yang melayani jaringan jasa penjualan, perawatan, perbaikan dan penyediaan suku cadang Toyota yang terbesar di seluruh Indonesia.</value>
      <webElementGuid>398abeb8-5cb5-404c-87cf-c60390907a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/div[@class=&quot;text-reliableBlack bg-[#f4f4f4] py-3 lg:py-11 flex justify-center&quot;]</value>
      <webElementGuid>67a4400b-3f69-4294-9d1f-70baa2ffdeea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[5]</value>
      <webElementGuid>637ea4e1-3bfa-4f89-8f9b-25b59565366d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[5]</value>
      <webElementGuid>dbd35a13-1322-45d0-90b1-56586a1669cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'AUTO2000 DIGIROOMDealer Toyota terbesar di Indonesia yang melayani jaringan jasa penjualan, perawatan, perbaikan dan penyediaan suku cadang Toyota yang terbesar di seluruh Indonesia.' or . = 'AUTO2000 DIGIROOMDealer Toyota terbesar di Indonesia yang melayani jaringan jasa penjualan, perawatan, perbaikan dan penyediaan suku cadang Toyota yang terbesar di seluruh Indonesia.')]</value>
      <webElementGuid>5017a7da-eb30-4202-829b-88c094891944</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
