<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Promo TerkaitLihat semuaAgya Generasi T_77c1f2</name>
   <tag></tag>
   <elementGuidId>11b9f24c-917f-4a68-85f0-fbc6be91ef75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>851cd364-ed91-4f82-b20a-0af0e2823aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lg:container </value>
      <webElementGuid>2ed1de02-f98c-4c2a-9f18-ac182cde218c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Promo TerkaitLihat semuaAgya Generasi Terbaru Lebih Canggih Sekaligus Ekonomis Page1 Jan 2024 - 1 Mar 2024Final test18 Des 2023 - 6 Jan 2024promo-testing11 Des 2023 - 11 Mar 2024Promo Sienta Akhir Tahun18 Des 2023 - 29 Des 2023</value>
      <webElementGuid>97570420-ab2b-4dae-bfaf-d51377b97214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/div[@class=&quot;lg:container&quot;]</value>
      <webElementGuid>ead43ea3-9ed1-47f2-9bd4-792123ed7229</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[3]</value>
      <webElementGuid>d4ab3156-c74a-4bf2-95d1-e2bab5c5b2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[3]</value>
      <webElementGuid>6478a93c-9940-4eb0-a6a7-8537bd0a653e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Promo TerkaitLihat semuaAgya Generasi Terbaru Lebih Canggih Sekaligus Ekonomis Page1 Jan 2024 - 1 Mar 2024Final test18 Des 2023 - 6 Jan 2024promo-testing11 Des 2023 - 11 Mar 2024Promo Sienta Akhir Tahun18 Des 2023 - 29 Des 2023' or . = 'Promo TerkaitLihat semuaAgya Generasi Terbaru Lebih Canggih Sekaligus Ekonomis Page1 Jan 2024 - 1 Mar 2024Final test18 Des 2023 - 6 Jan 2024promo-testing11 Des 2023 - 11 Mar 2024Promo Sienta Akhir Tahun18 Des 2023 - 29 Des 2023')]</value>
      <webElementGuid>2e33281d-76fb-43c5-a898-9530010331ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
