<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Bagikan</name>
   <tag></tag>
   <elementGuidId>74e35471-c5f3-4269-b3a3-49ab8bb7791c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>b51ccd24-fba1-4db4-be16-305339845024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-4 lg:py-8 bg-reliableBlack3</value>
      <webElementGuid>aa5813cd-e7e8-4714-9cee-0c399e11a0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bagikan :</value>
      <webElementGuid>5af511b2-01ef-4cb7-8fdd-a61ad1ef5c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/section[@class=&quot;py-4 lg:py-8 bg-reliableBlack3&quot;]</value>
      <webElementGuid>6e3d46ce-d89c-4609-a09a-948d7c09900e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section</value>
      <webElementGuid>bfb7e301-2225-431a-8cf1-f81c6e4cc1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/section</value>
      <webElementGuid>81493eda-b230-41e1-9749-1bdd10470290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = 'Bagikan :' or . = 'Bagikan :')]</value>
      <webElementGuid>ee2c2379-21f8-4c20-afef-d51649373f22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
