<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputdd-provinsi</name>
   <tag></tag>
   <elementGuidId>a01e9389-5c5c-42a0-8a8a-5405971f0950</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dd-provinsi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dd-provinsi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9122aafc-3135-4a4e-ab61-9d46bdcec271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dd-provinsi</value>
      <webElementGuid>a7a8046d-75ca-4272-acdf-23539692ce36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>58bbc3e1-efe4-49ac-b053-fddbe9da4d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none px-4 py-2 bg-reliableBlack3 text-reliableBlack border-b border-reliableBlack30 cursor-pointer placeholder:text-reliableBlack60 focus:border-reliableBlack60 lg:px-5 lg:py-4 bg-white border-[#5F5F5F] max-h-fit lg:max-h-fit focus:border-reliableBlack false</value>
      <webElementGuid>7199bc2c-8413-4fb3-8dd4-9fe5f4c2b4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Provinsi</value>
      <webElementGuid>0c8c988d-c917-4503-bbf7-9070381a0c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd-provinsi&quot;)</value>
      <webElementGuid>5f572ad2-4edb-4fa2-b633-aa41720b6a18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dd-provinsi']</value>
      <webElementGuid>c34907d5-e97b-4018-b0a8-b3ba2e4245d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[3]/div/div/div[2]/section/form/div[2]/div/div/input</value>
      <webElementGuid>4a80bece-5959-432f-80b7-b4ee99dbb455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>413943bc-141b-4c1c-a703-f67b100588d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dd-provinsi' and @type = 'text' and @placeholder = 'Pilih Provinsi']</value>
      <webElementGuid>8e78f3de-6793-4edc-9b11-9d1bd882502e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
