<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputdd-city</name>
   <tag></tag>
   <elementGuidId>bda42e67-1052-437e-9009-99ebb226cf68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dd-city']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dd-city</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6b2f211-154e-4653-bbbf-cc18b84d8c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dd-city</value>
      <webElementGuid>f71fcd1a-3683-4f38-aae8-edfda33f7840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f74d658-4543-483a-ae7d-6ef7b8fb212f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none px-4 py-2 bg-reliableBlack3 text-reliableBlack border-b border-reliableBlack30 cursor-pointer placeholder:text-reliableBlack60 focus:border-reliableBlack60 lg:px-5 lg:py-4 bg-white border-[#5F5F5F] max-h-fit lg:max-h-fit focus:border-reliableBlack false</value>
      <webElementGuid>c3028531-a703-49b3-a220-442f426b794e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Kota</value>
      <webElementGuid>1015c622-da99-4627-a91e-16e5b928c3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd-city&quot;)</value>
      <webElementGuid>910d1335-7b3e-4b52-b0ce-6a88bdd04a60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dd-city']</value>
      <webElementGuid>73468bf1-bfb1-4212-8bb4-87ea8a10445a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[3]/div/div/div[2]/section/form/div[3]/div/div/input</value>
      <webElementGuid>0efb77b8-bebd-4764-b52f-ecfec17f9f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>6bcd2612-95c4-49cd-a814-e5f2deb1ae6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dd-city' and @type = 'text' and @placeholder = 'Pilih Kota']</value>
      <webElementGuid>f49175e5-f5bd-4d30-85f9-e5195a450f21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
