<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Data pribadi Anda aman bersama kami Kebij_913c42</name>
   <tag></tag>
   <elementGuidId>3e554716-4dbf-4c4f-b66a-039f0c622391</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[3]/div/div/div[2]/section/form/div[6]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.flex-1.text-reliableBlack.font-normal.text-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>878f6e2c-4403-4b47-b232-6c92a9be2e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-1 text-reliableBlack font-normal text-sm</value>
      <webElementGuid>c10a3ab4-6213-4897-a0e2-53c8ffbbe49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data pribadi Anda aman bersama kami Kebijakan Privasi</value>
      <webElementGuid>3d379b5b-ca7b-4b00-a9d5-84c062e17f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;lg:container xl:px-0&quot;]/div[@class=&quot;grid grid-cols-1 gap-6 lg:grid-cols-[2fr_1fr]&quot;]/div[@class=&quot;container hidden md:mt-5 lg:p-0 md:block&quot;]/section[@class=&quot;bg-reliableBlack5 p-5&quot;]/form[@class=&quot;bg-inherit&quot;]/div[@class=&quot;flex items-center gap-4 mb-[18px] md:mb-7  pb-28 md:pb-0&quot;]/p[@class=&quot;flex-1 text-reliableBlack font-normal text-sm&quot;]</value>
      <webElementGuid>749e8667-531d-494d-8330-edbece6c6c8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[3]/div/div/div[2]/section/form/div[6]/p</value>
      <webElementGuid>351b27f7-9104-4927-895b-9cc23bcce786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/p</value>
      <webElementGuid>e947c4ec-188e-4d46-a070-96dcdc0723ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Data pribadi Anda aman bersama kami Kebijakan Privasi' or . = 'Data pribadi Anda aman bersama kami Kebijakan Privasi')]</value>
      <webElementGuid>b16c319d-dd6d-4c9a-ad9c-c6f6520ea982</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
