<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_mdmin-w-177.77px mdh-100px max-w-124.44_72cd6a</name>
   <tag></tag>
   <elementGuidId>8693a435-1282-4224-aed3-ead16fc39f97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='card-news-toyota-gr-sport---harga-spesifikasi-dan-promo-terbaru-2022--duplikat-1']/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>31092fc9-3e3b-4227-840c-6b382d7e1cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>25 2.webp</value>
      <webElementGuid>23270488-9fa6-4a90-9636-5a19fbad8d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>21a70796-cb8c-4ba1-b1bf-695755dfc8aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>ca1eeebd-23c8-4a95-be1f-c6c5491994c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>e5ef81b2-894e-4cbe-8879-c6f77be3a43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>933c6b07-7caa-409b-b10d-80bb79320e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>587a451c-9365-41f6-b57e-a0660c7de7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md:min-w-[177.77px] md:h-[100px] max-w-[124.44px] h-[70px] object-cover</value>
      <webElementGuid>edc67d7e-9e81-4715-aacc-23d6d86cf261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>150px</value>
      <webElementGuid>ad2da1f6-d4a5-47a7-9ba7-78c036eaf19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/berita-dan-tips/_next/image?url=https%3A%2F%2Fastradigitaldigiroomstg.blob.core.windows.net%2Fstorage-general-001%2F25%25202.webp&amp;w=16&amp;q=75 16w, /berita-dan-tips/_next/image?url=https%3A%2F%2Fastradigitaldigiroomstg.blob.core.windows.net%2Fstorage-general-001%2F25%25202.webp&amp;w=32&amp;q=75 32w, /berita-dan-tips/_next/image?url=https%3A%2F%2Fastradigitaldigiroomstg.blob.core.windows.net%2Fstorage-general-001%2F25%25202.webp&amp;w=48&amp;q=75 48w, /berita-dan-tips/_next/image?url=https%3A%2F%2Fastradigitaldigiroomstg.blob.core.windows.net%2Fstorage-general-001%2F25%25202.webp&amp;w=64&amp;q=75 64w, /berita-dan-tips/_next/image?url=https%3A%2F%2Fastradigitaldigiroomstg.blob.core.windows.net%2Fstorage-general-001%2F25%25202.webp&amp;w=96&amp;q=75 96w, /berita-dan-tips/_next/image?url=https%3A%2F%2Fastradigitaldigiroomstg.blob.core.windows.net%2Fstorage-general-001%2F25%25202.webp&amp;w=128&amp;q=75 128w, /berita-dan-tips/_next/image?url=https%3A%2F%2Fastradigitaldigiroomstg.blob.core.windows.net%2Fstorage-general-001%2F25%25202.webp&amp;w=256&amp;q=75 256w, /berita-dan-tips/_next/image?url=https%3A%2F%2Fastradigitaldigiroomstg.blob.core.windows.net%2Fstorage-general-001%2F25%25202.webp&amp;w=384&amp;q=75 384w, /berita-dan-tips/_next/image?url=https%3A%2F%2Fastradigitaldigiroomstg.blob.core.windows.net%2Fstorage-general-001%2F25%25202.webp&amp;w=640&amp;q=75 640w, /berita-dan-tips/_next/image?url=https%3A%2F%2Fastradigitaldigiroomstg.blob.core.windows.net%2Fstorage-general-001%2F25%25202.webp&amp;w=750&amp;q=75 750w, /berita-dan-tips/_next/image?url=https%3A%2F%2Fastradigitaldigiroomstg.blob.core.windows.net%2Fstorage-general-001%2F25%25202.webp&amp;w=828&amp;q=75 828w, /berita-dan-tips/_next/image?url=https%3A%2F%2Fastradigitaldigiroomstg.blob.core.windows.net%2Fstorage-general-001%2F25%25202.webp&amp;w=1080&amp;q=75 1080w, /berita-dan-tips/_next/image?url=https%3A%2F%2Fastradigitaldigiroomstg.blob.core.windows.net%2Fstorage-general-001%2F25%25202.webp&amp;w=1200&amp;q=75 1200w, /berita-dan-tips/_next/image?url=https%3A%2F%2Fastradigitaldigiroomstg.blob.core.windows.net%2Fstorage-general-001%2F25%25202.webp&amp;w=1920&amp;q=75 1920w, /berita-dan-tips/_next/image?url=https%3A%2F%2Fastradigitaldigiroomstg.blob.core.windows.net%2Fstorage-general-001%2F25%25202.webp&amp;w=2048&amp;q=75 2048w, /berita-dan-tips/_next/image?url=https%3A%2F%2Fastradigitaldigiroomstg.blob.core.windows.net%2Fstorage-general-001%2F25%25202.webp&amp;w=3840&amp;q=75 3840w</value>
      <webElementGuid>4996bcf6-a6c2-420d-b9f0-19388e802cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/berita-dan-tips/_next/image?url=https%3A%2F%2Fastradigitaldigiroomstg.blob.core.windows.net%2Fstorage-general-001%2F25%25202.webp&amp;w=3840&amp;q=75</value>
      <webElementGuid>8aa4c0bf-2d78-4990-9f12-c7c04f46549e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-news-toyota-gr-sport---harga-spesifikasi-dan-promo-terbaru-2022--duplikat-1&quot;)/div[@class=&quot;border-b-[0.5px] border-[#E9E9E9] lg:-mt-8&quot;]/div[@class=&quot;flex justify-start md:gap-3 gap-2 pt-2 px-4 pb-4&quot;]/img[@class=&quot;md:min-w-[177.77px] md:h-[100px] max-w-[124.44px] h-[70px] object-cover&quot;]</value>
      <webElementGuid>646f1641-74b7-456f-b5b1-175dc0f2a517</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='card-news-toyota-gr-sport---harga-spesifikasi-dan-promo-terbaru-2022--duplikat-1']/div/div[2]/img</value>
      <webElementGuid>2e3389c4-6e48-4505-93c4-83d3c39ae7c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='25 2.webp']</value>
      <webElementGuid>41904c6c-a7e3-4e8a-8864-57d66b763ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/div/div[2]/img</value>
      <webElementGuid>8943bf89-4512-4ab2-b80d-af133c628806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = '25 2.webp' and @src = '/berita-dan-tips/_next/image?url=https%3A%2F%2Fastradigitaldigiroomstg.blob.core.windows.net%2Fstorage-general-001%2F25%25202.webp&amp;w=3840&amp;q=75']</value>
      <webElementGuid>cb30e317-89b8-4679-b60a-fbed45b54b2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
