<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Informasi Berita dan Artikel Otomotif Mo_1286d8</name>
   <tag></tag>
   <elementGuidId>6fc77890-c534-4762-b791-8944dde5e122</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section[2]/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>f0133131-3a34-4082-9c7b-60af7b86ca33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base font-bold text-reliableBlack uppercase mb-4 lg:text-2xl lg:mb-2</value>
      <webElementGuid>67594012-27ea-4abd-802c-1a62e2ab2cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Informasi Berita dan Artikel Otomotif Mobil Auto2000 2024</value>
      <webElementGuid>8f63ce27-ed3c-4948-bf1d-d82421ccb262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/section[@class=&quot;my-10 lg:my-20&quot;]/div[@class=&quot;container xl:px-0&quot;]/h2[@class=&quot;text-base font-bold text-reliableBlack uppercase mb-4 lg:text-2xl lg:mb-2&quot;]</value>
      <webElementGuid>fe87ddda-5edd-48a4-a7e3-3d712f52ae42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section[2]/div/h2</value>
      <webElementGuid>3ca797ef-a75f-40a7-9704-364c6be8bab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>3798af46-af55-4566-8bb8-1833543aebb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Informasi Berita dan Artikel Otomotif Mobil Auto2000 2024' or . = 'Informasi Berita dan Artikel Otomotif Mobil Auto2000 2024')]</value>
      <webElementGuid>41359260-9146-4ad1-99bd-59726d569618</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
