<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Dapatkan informasi terkini melalui berita_a7ef9d</name>
   <tag></tag>
   <elementGuidId>b2a8fa34-003d-4494-b11d-3fa4b5a0cb54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f8dead15-5018-4fe5-b07e-ea5beb0f048f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-xs font-medium leading-relaxed text-reliableBlack lg:text-base</value>
      <webElementGuid>fd6efc43-1d40-4e8d-9f7b-76d35fcad53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dapatkan informasi terkini melalui berita eksklusif dan tips dari Auto2000</value>
      <webElementGuid>93c245de-051d-4b58-aff1-78e945006805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;bg-white&quot;]/section[@class=&quot;lg:my-[20px]&quot;]/div[@class=&quot;lg:container xl:px-0&quot;]/div[@class=&quot;container lg:p-0&quot;]/p[@class=&quot;text-xs font-medium leading-relaxed text-reliableBlack lg:text-base&quot;]</value>
      <webElementGuid>5e403cfd-5735-453c-b600-ae657af499a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div/div/p</value>
      <webElementGuid>62a06e97-31a2-4c75-ad72-173310f4038a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/p</value>
      <webElementGuid>667d51df-f078-4959-a35f-2d0acdbb1819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Dapatkan informasi terkini melalui berita eksklusif dan tips dari Auto2000' or . = 'Dapatkan informasi terkini melalui berita eksklusif dan tips dari Auto2000')]</value>
      <webElementGuid>7114f5f5-ad7c-4481-b40a-458c9c20a6eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
